config/routes.rb
Rails.application.routes.draw do
  resources :requests
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :employees, :users, :admin_users
  

  root to: 'users#show'

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
    get '/users/:id' => "users#show", :as => :profile
    get '/users/:id/edit' => "users#edit", :as => :edit
    get '/requests/new' => "requests#new", :as => :leaverequest
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/request.rb
class Request < ActiveRecord::Base
    belongs_to :user
#    default_scope -> { order(created_at: :desc) }
#    validates :id, presence: true
    validates :user_id, presence: true
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :requests, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def http_protocol 
  if website.present?
    self.website = "http://#{self.website}" unless website[/\Ahttps?:\/\//]
  end
  end       
         
         
  def employee_name
    f_name + " " + l_name
  end
  
  def user_id
    id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  before_filter do
  resource = controller_name.singularize.to_sym
  method = "#{resource}_params"
  params[resource] &&= send(method) if respond_to?(method, true)
end

# Defining a variable which allows us to call the users full name.

  def employee_name
    f_name + " " + l_name
  end

# The below statement is ensuring that if the user is NOT logged in, no matter where in the application it will reroute to the login page.
# If they are logged in, it will default to the routes.rb file and the root to: that is set in there.

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to login_path, :notice => 'You are not signed in!'
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end

end

app/controllers/requests_controller.rb
class RequestsController < InheritedResources::Base
  # The below before_filter is set across the application to ensure that no pages can be accessed without an authenticated user being logged in.
    before_filter :authenticate_user!
    
  # defining the show method for requests which assists with the association between a User object and a Request object.  
    
    def show
      @request = Request.includes(:user).find(params[:id])
    end
    
  # passing the permitted paramaters for a Request to allow writing to the database.

    def request_params
      params.require(:request).permit(:employee_name, :date_begin, :date_end, :leave_type, :user_id, :id, :status)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
 # Sessions controller was generated to resolve Devise routing errors.
 
 # The below Create method was defined to assist the sign_in function.
    def create
        @sessions = session.new
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!



  def index
    @users = User.all
  end
  
# the below show method tells Rails to display the currently signed in user upon the Show action. 
# The if statement also allows the users associated requests to be shown within the users routes.

  def show
    @user = current_user
    if @user 
      @request = @user.requests.all
      render action: :show
    end
  end
    
#    @request = Request.find(current_user.user_id)
#    @request = Request.find(@user.user_id)
#    end

  
  
  def new
    @user = User.new
  end

# The create method below passes the appropraite user parameters when creating a new user and automatically signs the user in, displaying a message.

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  # Edits the currently signed in user.

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:f_name, :email, :password,
                                   :password_confirmation, :l_name, :address, :phone, :sex, :start_date, :dept, :role, :salary, :manager, :notes, :id, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>HR CloudApp</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
 <div id='header'>
 <!-- Header Image Displayes here -->
 <div id='logo'>
<strong>HR CloudApp</strong></div>
 <div id='student'>
  <strong>x14124807</strong>
 </div>
 <p class="navbar-text pull-right">

<% if user_signed_in? %>
  Welcome <strong><%= current_user.employee_name %></strong>.
  <%= link_to 'Edit Employee Profile', edit_path(current_user), :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>

<% end %>
 </div>
 <div id='menu'>
 <div id="navbar">
<ul>
<!-- I have configured the navbar below to display only the Login option and a link to the Admin console if the user is not signed in. 
 When the user is signed in, the option to see Leave Requests etc. becomes visible. -->
<li><a href="/admin/dashboard">Administration</a></li>
<% if user_signed_in? %>
<li><%= link_to "Employee Profile", current_user %></li>
<li><%= link_to "Leave Requests", leaverequest_path %></li>
<% else %>
<li><%= link_to "Login", login_path %></li>
<% end %>
</ul>
 </div>
 </div>
 <div id='container'>
 <div id='content'>
 <p class="notice"><%= flash[:notice] %></p>
 <%= yield %>
</div>
 
 <div id='footer'>
 <h6 class="footertext">&copy; HR CloudApp &trade; 2015</h6>
 </div>
</body>
</html>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- The below fields, "Employee ID" and "Employee Name" are configured to automatically pull in the required info from the logged in user.
        They are also set to read only so that the user can not change them or submit requests on behalf of another. -->
  <div class="field">
    <%= f.label :user_id, "Employee ID" %><br>
    <%= f.text_field :user_id, required: true, class: 'form-control', value:current_user.user_id, :readonly => true %>
  </div>
  

  <div class="field">
    <%= f.label :employee_name %><br>
    <%= f.text_field :employee_name, required: true, class: 'form-control', value:current_user.employee_name, :readonly => true %>

  </div>
  <div class="field">
    <%= f.label :date_begin %><br>
    <%= f.date_select :date_begin %>
  </div>
  <div class="field">
    <%= f.label :date_end %><br>
    <%= f.date_select :date_end %>
  </div>
  <div class="field">
    <%= f.label :leave_type %><br>
    <%= f.select :leave_type, [['Annual Leave', 'annual leave'],['Sick Leave', 'sick leave'],['Force Majeure', 'force majeure'],['Study Leave', 'study leave'],['Maternity Leave', 'maternity leave']] %>
  </div>
  
<!-- The below hidden field is set up to set the status of the Leave Reqeust to "Pending" by default. 
This can only be changed by an admin user in the admin console. -->
    <%= f.hidden_field :status, required: true, class: 'form-control', value:"Pending", include_blank: false, :readonly => true %>

  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/_request.html.erb
<li id="request-<%= request.id %>">
  <span class="user"><%= link_to request.user.name, request.user %></span>
  <span class="date_begin"><%= request.date_begin %></span>
  </span>
</li>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', current_user %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Employee name</th>
      <th>Date begin</th>
      <th>Date end</th>
      <th>Leave type</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.employee_name %></td>
        <td><%= request.date_begin %></td>
        <td><%= request.date_end %></td>
        <td><%= request.leave_type %></td>
        <td><%= request.status %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Leave Request</h1>

<%= render 'form' %>

<%= link_to 'Back', current_user %>

app/views/requests/show.html.erb
<p>
  <strong>Employee Name:</strong>
  <%= @request.employee_name %>
</p>

<p>
  <strong>Date Commencing:</strong>
  <%= @request.date_begin %>
</p>

<p>
  <strong>Date Ending:</strong>
  <%= @request.date_end %>
</p>

<p>
  <strong>Leave Type:</strong>
  <%= @request.leave_type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.status %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', current_user %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- I have limited the amount of details that the employee has the ability to edit.
All information can be edited by administrators in the admin console. -->

  <div class="field">
    <%= f.label :f_name, "First Name" %><br>
    <%= f.text_field :f_name %>
  </div>
  <div class="field">
    <%= f.label :l_name, "Last Name" %><br>
    <%= f.text_field :l_name %>
  </div>
  <div class="field">
    <%= f.label :address, "Address" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone, "Phone" %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.select :sex, [['Male', 'male'],['Female', 'female']] %>
  </div>
  <div class="field">
    <%= f.label :dob, "Date of birth" %><br>
    <%= f.date_select :dob %>
  </div>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @user %>

app/views/users/index.html.erb
<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      
      <th>F name</th>
      <th>L name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Sex</th>
      <th>Dob</th>
      <th>Start date</th>
      <th>Dept</th>
      <th>Role</th>
      <th>Salary</th>
      <th>Manager</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @users %>
    <% @users.each do |user| %>
      <tr>

        <td><%= user.f_name %></td>
        <td><%= user.l_name %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.sex %></td>
        <td><%= user.dob %></td>
        <td><%= user.start_date %></td>
        <td><%= user.dept %></td>
        <td><%= user.role %></td>
        <td><%= user.salary %></td>
        <td><%= user.manager %></td>
        <td><%= user.notes %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/users/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/users/show.html.erb
<div id="profile">
  
<h1>Employee Profile</h1>

<p>
  <strong>First name:</strong>
  <%= @user.f_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.l_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @user.start_date %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user.dept %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @user.salary %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @user.manager %>
</p>

<p>
  <strong>Notes/Comments:</strong>
  <%= @user.notes %>
</p>

<!-- The below section is set up to display any Active Leave requests that the user currently has.
This is determined depending on the Request Status being set to "Pending". -->

<p>
  <strong><h3>Active Leave Requests:</h3></strong><br>

  <% @request.each do |request| %>
  <% if request.status == "Pending" %>
<table style="width:100%">
  <tr>
    
<td>
  <strong>Employee Name:</strong></td>
<td>
  <strong>Date Commencing:</strong></td>
<td>
  <strong>Date Ending:</strong></td>
<td>
  <strong>Leave Type:</strong></td>
<td>
  <strong>Status:</strong></td>
  </tr>
  
  <tr>
  <td>
  <%= request.employee_name %></td>

  <td>
  <%= request.date_begin %></td>
  
  <td>
  <%= request.date_end %></td>
  
  <td>
  <%= request.leave_type %></td>
  
  <td>
  <%= request.status %></td>
  | <%= link_to 'Edit', edit_request_path(request) %> |
  </tr>

  </table>
    <% end %>
    <% end %>
<br>

<!-- If the status of the request is anything other than "Pending" it will go into the Closed Requests section. -->
<p>
  <strong><h3>Closed Leave Requests:</h3></strong><br>
  <br>
  <% @request.each do |request| %>
  <% if request.status != "Pending" %>
<table style="width:100%">
  <tr>
    
<td>
  <strong>Employee Name:</strong></td>
<td>
  <strong>Date Commencing:</strong></td>
<td>
  <strong>Date Ending:</strong></td>
<td>
  <strong>Leave Type:</strong></td>
<td>
  <strong>Status:</strong></td>
  </tr>
  
  <tr>
  <td>
  <%= request.employee_name %></td>

  <td>
  <%= request.date_begin %></td>
  
  <td>
  <%= request.date_end %></td>
  
  <td>
  <%= request.leave_type %></td>
  
  <td>
  <%= request.status %></td>
  </tr>
  </table>
    <% end %>
  <% end %>

<br>


<%= link_to 'Edit Employee Profile', edit_path(@user) %>
</div>